sudo: false

language: php
php:
  - 'master'
  - '7.3'
  - '7.2'
  - '7.1'
  - '7.0'
  - '5.6'
  - '5.5'

git:
  depth: 1

addons:
  apt:
    packages:
      - valgrind
      - gdb
      - lcov

compiler:
  - gcc

matrix:
  fast_finish: true
  allow_failures:
    - php: 'master'

cache:
  apt: true
  timeout: 604800
  directories:
    - ${HOME}/.local/opt/re2c
    - ${HOME}/.cache/re2c

env:
  global:
    - CFLAGS="-g -O0 -Wall -fvisibility=hidden"
    - ZEND_DONT_UNLOAD_MODULES=1
    - USE_ZEND_ALLOC=0
    - REPORT_EXIT_STATUS=1
    - NO_INTERACTION=1
    - RE2C_VERSION="1.1.1"

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - ./.ci/install-re2c.sh
  - ./install-development --phpize $(phpenv which phpize) --php-config $(phpenv which php-config)

script:
  - ./.ci/run-tests.sh

jobs:
  include:
    - stage: re2c versions test
      php: 7.2
      env:
        - RE2C_VERSION="0.13.6"
      compiler:
        - gcc
      install:
        - ./.ci/install-re2c.sh
        - ./install-development --phpize $(phpenv which phpize) --php-config $(phpenv which php-config)
      script:
        - ./.ci/run-tests.sh
    - stage: Clang test
      php: 7.2
      env:
        - RE2C_VERSION="0.13.6"
      compiler:
        - clang
      install:
        - ./.ci/install-re2c.sh
        - ./install-development --phpize $(phpenv which phpize) --php-config $(phpenv which php-config)
      script:
        - ./.ci/run-tests.sh
    - stage: Clang test
      php: 7.3
      compiler:
        - clang
      install:
        - ./.ci/install-re2c.sh
        - ./install-development --phpize $(phpenv which phpize) --php-config $(phpenv which php-config)
      script:
        - ./.ci/run-tests.sh

after_failure:
  - ./.ci/after-failure.sh

after_success:
  - if [[ ! -z "${CODECOV_TOKEN}" ]]; then bash <(curl -s https://codecov.io/bash); fi;

notifications:
  email: false
