sudo: false

language: php
php:
  - 'master'
  - '7.3'
  - '7.2'
  - '7.1'
  - '7.0'
  - '5.6'
  - '5.5'

git:
  depth: 1

addons:
  apt:
    packages:
      - valgrind
      - gdb
      - lcov

compiler: gcc

matrix:
  fast_finish: true
  allow_failures:
    - php: 'master'

cache:
  apt: true
  timeout: 604800
  directories:
    - ${HOME}/.local/opt/re2c
    - ${HOME}/.cache/re2c

env:
  global:
    - CFLAGS="-g -O0 -Wall -fvisibility=hidden"
    - RE2C_VERSION="1.1.1"
    - REPORT_COVERAGE=1

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry gem install coveralls-lcov
  - ulimit -c unlimited -S

install:
  - .ci/install-re2c.sh
  - .ci/build.sh

before_script:
  - lcov --directory $(pwd)/parser --directory $(pwd) --zerocounters
  - lcov --directory $(pwd)/parser --directory $(pwd) --capture --compat-libtool --initial --output-file coverage.info

script:
  - .ci/run-tests.sh

jobs:
  include:
    - stage: re2c versions test
      php: 7.2
      env:
        - RE2C_VERSION="0.13.6"
      install:
        - .ci/install-re2c.sh
        - .ci/build.sh
      script:
        - .ci/run-tests.sh
    - stage: Clang test
      php: 7.2
      env:
        - RE2C_VERSION="0.13.6"
      compiler: clang
      install:
        - .ci/install-re2c.sh
        - .ci/build.sh
      script:
        - .ci/run-tests.sh
    - stage: Clang test
      php: 7.2
      env:
        - RE2C_VERSION="system"
      compiler: clang
      install:
        - .ci/install-re2c.sh
        - .ci/build.sh
      script:
        - .ci/run-tests.sh
    - stage: Clang test
      php: 7.3
      compiler: clang
      install:
        - .ci/install-re2c.sh
        - .ci/build.sh
      script:
        - .ci/run-tests.sh

after_failure:
  - .ci/after-failure.sh

after_success:
  - .ci/after-success.sh

notifications:
  email: false
